include: ../analysis_options.yaml
analyzer:
  language:
    strict-inference: false
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    unused_element: ignore
    unnecessary_import: ignore
    deprecated_member_use: ignore
    unused_element_parameter: ignore
    unnecessary_null_comparison: ignore
    inference_failure_on_instance_creation: ignore
    dead_code: ignore
